<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="JWT\" />
    <Folder Include="Migrations\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SqlSugarCore" Version="5.1.4.178" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MeetingRoom.Domain\MRR.Domain.csproj" />
    <ProjectReference Include="..\MeetingRoom.Shared\MRR.Shared.csproj" />
  </ItemGroup>

</Project>
